#include "shader_cache.hpp"

#import <Metal/Metal.h>
#import <Foundation/Foundation.h>

#include <stdexcept>
#include <sstream>

namespace mlx_mfa {

// Singleton
ShaderCache& ShaderCache::get() {
  static ShaderCache instance;
  return instance;
}

// KernelKey hashing and equality

bool ShaderCache::KernelKey::operator==(const KernelKey& other) const {
  return type == other.type &&
         head_dim == other.head_dim &&
         block_q == other.block_q &&
         block_k == other.block_k &&
         block_d == other.block_d &&
         n_warps == other.n_warps &&
         causal == other.causal &&
         bf16_emulation == other.bf16_emulation &&
         dtype == other.dtype;
}

size_t ShaderCache::KernelKeyHash::operator()(const KernelKey& k) const {
  // FNV-1a hash (mirrors ccv_nnc_mfa_hash.hpp)
  size_t h = 14695981039346656037ULL;
  auto mix = [&h](uint64_t val) {
    h ^= val;
    h *= 1099511628211ULL;
  };
  mix(static_cast<uint64_t>(k.type));
  mix(static_cast<uint64_t>(k.head_dim));
  mix(static_cast<uint64_t>(k.block_q));
  mix(static_cast<uint64_t>(k.block_k));
  mix(static_cast<uint64_t>(k.block_d));
  mix(static_cast<uint64_t>(k.n_warps));
  mix(static_cast<uint64_t>(k.causal));
  mix(static_cast<uint64_t>(k.bf16_emulation));
  mix(static_cast<uint64_t>(k.dtype));
  return h;
}

// get_or_compile

void* ShaderCache::get_or_compile(const KernelKey& key, void* device) {
  auto it = cache_.find(key);
  if (it != cache_.end()) {
    return it->second;
  }

  auto source = generate_shader_source(key);
  std::string fn_name;
  switch (key.type) {
    case KernelKey::KernelType::AttentionForward:
      fn_name = "attention_forward"; break;
    case KernelKey::KernelType::AttentionBackwardDQ:
      fn_name = "attention_backward_dq"; break;
    case KernelKey::KernelType::AttentionBackwardDKV:
      fn_name = "attention_backward_dkv"; break;
  }

  auto* pipeline = compile_shader(source, fn_name, device);
  cache_[key] = pipeline;
  return pipeline;
}

// JIT shader generation (placeholder)

std::string ShaderCache::generate_shader_source(const KernelKey& key) {
  // -------------------------------------------------------------------
  // TODO(Phase 1.2): Port JIT generation from ccv source:
  //   liuliu/ccv/lib/nnc/mfa/v2/  (kernel templates)
  //   liuliu/ccv/lib/nnc/mfa/ccv_nnc_mfa_attention.cpp
  //
  // Key sections of generated shader:
  //   1. Threadgroup memory: Q/K/V tiles, accumulators
  //   2. Online softmax: m_i (running max), l_i (running sum)
  //   3. Main loop over K/V tiles:
  //      a. Load K tile (simdgroup_async_copy on A14+)
  //      b. S = Q_tile @ K_tile^T (SIMD FMA)
  //      c. Causal mask
  //      d. Online softmax update
  //      e. Load V tile
  //      f. O += softmax(S) @ V_tile
  //   4. Write O and logsumexp L
  // -------------------------------------------------------------------

  std::ostringstream oss;
  oss << "// AUTO-GENERATED by mlx-mfa ShaderCache\n"
      << "// D=" << key.head_dim
      << " Bq=" << key.block_q
      << " Bk=" << key.block_k
      << " causal=" << key.causal
      << " bf16_emu=" << key.bf16_emulation
      << "\n\n"
      << "#include <metal_stdlib>\n"
      << "using namespace metal;\n\n"
      << "// TODO: Full kernel (Phase 1.2)\n"
      << "kernel void attention_forward() {\n"
      << "  // Placeholder\n"
      << "}\n";

  return oss.str();
}

// Metal shader compilation (Objective-C Metal API)

void* ShaderCache::compile_shader(
    const std::string& source,
    const std::string& function_name,
    void* raw_device) {
  @autoreleasepool {
    id<MTLDevice> device = (__bridge id<MTLDevice>)raw_device;
    NSError* error = nil;

    NSString* src = [NSString stringWithUTF8String:source.c_str()];
    MTLCompileOptions* opts = [[MTLCompileOptions alloc] init];

    id<MTLLibrary> library = [device newLibraryWithSource:src
                                                  options:opts
                                                    error:&error];
    if (!library) {
      std::string msg = "Metal compilation failed";
      if (error) {
        msg += ": ";
        msg += [[error localizedDescription] UTF8String];
      }
      throw std::runtime_error(msg);
    }

    NSString* fnName = [NSString stringWithUTF8String:function_name.c_str()];
    id<MTLFunction> function = [library newFunctionWithName:fnName];
    if (!function) {
      throw std::runtime_error(
          "Metal function '" + function_name + "' not found");
    }

    id<MTLComputePipelineState> pipeline =
        [device newComputePipelineStateWithFunction:function error:&error];
    if (!pipeline) {
      std::string msg = "Pipeline creation failed";
      if (error) {
        msg += ": ";
        msg += [[error localizedDescription] UTF8String];
      }
      throw std::runtime_error(msg);
    }

    // Retain and return as void* (caller manages lifetime)
    return (__bridge_retained void*)pipeline;
  }
}

// clear

void ShaderCache::clear() {
  for (auto& [_, pipeline] : cache_) {
    if (pipeline) {
      CFRelease(pipeline);
    }
  }
  cache_.clear();
}

}  // namespace mlx_mfa
